[book]
title = "DeFi Protocol Engineering"
authors = ["torof"]
language = "en"
src = "docs"

[build]
build-dir = "book"
create-missing = false

[output.html]
search.enable = true
default-theme = "navy"
preferred-dark-theme = "navy"
additional-css = ["theme/custom.css"]
additional-js = ["theme/solidity-highlight.js", "theme/callouts.js"]
